# frozen_string_literal: true

require 'shellwords'

require 'gtk4'
require 'adwaita'
require 'vte4'

require_relative 'console_rb/version'
require_relative 'console_rb/i18n'
require_relative 'console_rb/shortcuts'
require_relative 'console_rb/regex'
require_relative 'console_rb/palette'
require_relative 'console_rb/livery'
require_relative 'console_rb/settings'
require_relative 'console_rb/process_info'
require_relative 'console_rb/train'
require_relative 'console_rb/empty'
require_relative 'console_rb/terminal'
require_relative 'console_rb/drop_target'
require_relative 'console_rb/tab'
require_relative 'console_rb/close_dialog'
require_relative 'console_rb/pages'
require_relative 'console_rb/theme_switcher'
require_relative 'console_rb/fullscreen_box'
require_relative 'console_rb/preferences_dialog'
require_relative 'console_rb/shortcuts_dialog'
require_relative 'console_rb/about_dialog'
require_relative 'console_rb/window'
require_relative 'console_rb/cli'
require_relative 'console_rb/application'
require_relative 'console_rb/launcher'
